// this file was autogenerated by go generate, do not edit
// Copyright (C) 2013 - 2016 - Oscar Campos <oscar.campos@member.fsf.org>
// This program is Free Software see LICENSE file for details

package main

var anaGondaBinaryPath = "/home/damnwidget/development/anaconda/anaconda_go/plugin/handlers_go/anagonda/bin/anaGonda-0.1.0.bin"
var anaGondaVersion = "0.1.0"
