
# Copyright (C) 2013 - 2016 - Oscar Campos <oscar.campos@member.fsf.org>
# This program is Free Software see LICENSE file for details

import os

# Plugin version
src_directory = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.dirname(src_directory))))
# root = os.path.dirname(os.path.dirname(os.path.dirname(filename)))
with open(os.path.join(root, 'messages.json'), 'r') as message_file:
    message_data = message_file.read()

ver = message_data.splitlines()[-2].split(':')[0].strip().replace('"', '')

tpl = '''// this file was autogenerated by go generate, do not edit
// Copyright (C) 2013 - 2016 - Oscar Campos <oscar.campos@member.fsf.org>
// This program is Free Software see LICENSE file for details

package main

var anaGondaBinaryPath = "{anagonda_path}"
var anaGondaVersion = "{anagonda_version}"
'''

with open('anagonda_config.go', 'w') as f:
    tpl_data = {
        'anagonda_path': os.path.join(
            os.path.dirname(src_directory), 'bin', 'anaGonda-{}.bin'.format(ver)),  # noqa
        'anagonda_version': ver
    }

    f.write(tpl.format(**tpl_data))
