<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>go</string>
	</array>
	<key>firstLineMatch</key>
	<string>-[*]-( Mode:)? Go -[*]-</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>AnacondaGO</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct-literal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=\bfunc\s+\()</string>
			<key>end</key>
			<string>(?=\{)</string>
			<key>name</key>
			<string>meta.function.method.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.method.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.language.this.go</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.method.go</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.method.go</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.go</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(func)\s+(\()\s*([A-Za-z0-9_]+)\s+(\*)?\s*([[:alnum:]_]+)\s*(\))\s+([a-zA-Z0-9_]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.method.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.method.go</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.go</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.type.go</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.pointer.go</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.package.go</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b([a-zA-Z0-9_]+)[\s\t]+((\*)?(?:([a-zA-Z0-9_]+)(\.))?[a-zA-Z0-9_]+)\b</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b[a-zA-Z0-9_]+\b</string>
							<key>name</key>
							<string>variable.parameter.go</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.definition.param-list.go</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.go</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.initialize.go</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This matches the 'x := 0' style of variable declaration.</string>
			<key>match</key>
			<string>(?:[[:alpha:]_][[:alnum:]_]*)(?:,\s+[[:alpha:]_][[:alnum:]_]*)*\s*(:=)</string>
			<key>name</key>
			<string>meta.initialization.short.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(func)\b</string>
			<key>name</key>
			<string>storage.type.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\Afunc|...\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\sfunc|....\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\Afunc|...\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var-and-const-blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var-and-const-statements</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|cap|close|complex|copy|delete|imag|len|make|new|panic|print|println|real|recover)\b</string>
			<key>name</key>
			<string>support.function.builtin.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable-dot-access</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignment-expr</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.type.builtin.go</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\[\])(&amp;)?(bool|byte|complex(64|128)|error|float(32|64)|rune|string|u?int(8|16|32|64)?|uintptr)\s*(?=\{)</string>
					<key>name</key>
					<string>meta.definition.array.go</string>
				</dict>
			</array>
		</dict>
		<key>assignment-expr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s(=)[\s\t]+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.assignment-expr.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtin-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(bool|byte|complex(64|128)|error|float(32|64)|rune|string|u?int(8|16|32|64)?|uintptr)\b</string>
					<key>name</key>
					<string>storage.type.builtin.go</string>
				</dict>
			</array>
		</dict>
		<key>chan-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\&lt;\-\s?)?chan(\s?\&lt;\-)?[\s\t]</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.chan.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.chan.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s|\t|$|,|;|\})</string>
					<key>name</key>
					<string>storage.type.chan.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.go</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>\z</string>
					<key>name</key>
					<string>comment.line.double-slash.go</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|nil|iota)\b</string>
					<key>name</key>
					<string>constant.language.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((\d+\.(\d+)?([eE][+-]?\d+)?|\d+[eE][+-]?\d+|\.\d+([eE][+-]?\d+)?)i?)\b</string>
					<key>name</key>
					<string>constant.numeric.floating-point.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\d+i|0[xX][0-9A-Fa-f]+|0[0-7]*|[1-9][0-9]*)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'(?:[^'\\]|\\(?:\\|[abfnrtv']|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3}))'</string>
					<key>name</key>
					<string>constant.other.rune.go</string>
				</dict>
			</array>
		</dict>
		<key>embedded-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.pointer.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.package.go</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.name.type.go</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[\s\t]*((\*)?(?:([a-zA-Z0-9_]+)(\.))?[a-zA-Z0-9_]+)[\s\t]*$</string>
					<key>name</key>
					<string>meta.declaration.field.embedded.go</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
			</array>
		</dict>
		<key>function-call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?:[a-zA-Z0-9_]+(\.))*([a-zA-Z0-9_]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dot-access.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.function-call.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.function-call.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function-call.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface-declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z0-9_]+)\s+(?=interface\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface-type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(interface)\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.interface.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.interface.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.interface.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b([a-zA-Z0-9_]+)(\()</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.go</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.function.go</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.function.go</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-type</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.pointer.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\.)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A subset of keyword.other.go for flow control keywords.</string>
					<key>match</key>
					<string>\b(break|case|continue|default|defer|else|fallthrough|for|go|goto|if|range|return|select|switch)\b</string>
					<key>name</key>
					<string>keyword.control.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(import|package)\b</string>
					<key>name</key>
					<string>keyword.other.go</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slice-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pointer-literal</string>
				</dict>
			</array>
		</dict>
		<key>map-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.go</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(map)(\[)(\w+)(\])</string>
					<key>name</key>
					<string>storage.type.map.go</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(&lt;-)</string>
					<key>name</key>
					<string>keyword.operator.channel.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;|&lt;=|&gt;|&gt;=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;&amp;|[|]{2}|!)</string>
					<key>name</key>
					<string>keyword.operator.logical.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([+]{2})</string>
					<key>name</key>
					<string>keyword.operator.increment.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(--)</string>
					<key>name</key>
					<string>keyword.operator.decrement.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([+]|-|[*]|/|%|&amp;|[|]|^|&amp;^|&lt;&lt;|&gt;&gt;)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(;)</string>
					<key>name</key>
					<string>keyword.operator.semi-colon.go</string>
				</dict>
			</array>
		</dict>
		<key>pointer-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&amp;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.pointer.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[^a-zA-Z0-9_\.])</string>
					<key>name</key>
					<string>meta.literal.pointer.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#struct-literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#slice-literal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(,)</string>
					<key>name</key>
					<string>punctuation.definition.comma.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([.])</string>
					<key>name</key>
					<string>punctuation.definition.dot.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(:)</string>
					<key>name</key>
					<string>punctuation.definition.colon.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\[|\]|{|}|\(|\))</string>
					<key>name</key>
					<string>punctuation.definition.bracket.go</string>
				</dict>
			</array>
		</dict>
		<key>slice-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[\])?(\*)?(?:([a-zA-Z0-9_]+)(\.))?([A-Za-z0-9_]+)(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.slice.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.pointer.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.package.go</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.go</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.slice.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.slice.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.literal.slice.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(,)</string>
							<key>name</key>
							<string>punctuation.separator.sequence.go</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>slice-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.slice.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s|$)</string>
					<key>name</key>
					<string>storage.type.slice.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>storage-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interface-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#chan-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slice-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#map-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin-type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.pointer.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.package.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.go</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>userland type</string>
					<key>match</key>
					<string>\b(\*)?(?:([a-zA-Z0-9_]+)(\.))?[a-zA-Z0-9_]+\b</string>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abfnrtv'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
					<key>name</key>
					<string>constant.character.escape.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.go</string>
				</dict>
			</array>
		</dict>
		<key>string_placeholder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)%
(\d+\$)?                                    # field (argument #)
[#0\- +']*                                  # flags
[,;:_]?                                     # separator character (AltiVec)
((-?\d+)|\*(-?\d+\$)?)?                     # minimum field width
(\.((-?\d+)|\*(-?\d+\$)?)?)?                # precision
[diouxXDOUeEfFgGaAcCsSqpnvtTbyYhHmMzZ%]     # conversion type</string>
					<key>name</key>
					<string>constant.other.placeholder.go</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.raw.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.gotemplate</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct-declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z0-9_]+)\s+(?=struct\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#struct-type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct-field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^[\s\t]*([a-zA-Z0-9_]+)[\s\t]+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.struct-field.go</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>storage.type.go</string>
					<key>end</key>
					<string>(?=$|`)</string>
					<key>name</key>
					<string>meta.definition.struct-field.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&amp;)?(?:([a-zA-Z0-9_]+)(\.))?([A-Za-z0-9_]+)(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.pointer.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.package.go</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.go</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.struct.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.struct.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.literal.struct.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#struct-literal-field</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(,)</string>
							<key>name</key>
							<string>punctuation.separator.mapping.go</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct-literal-field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.definition.struct-field.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.struct-field.go</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:([a-zA-Z0-9_]+)\s*(:))?</string>
				</dict>
			</array>
		</dict>
		<key>struct-tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.tag.struct-field.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.struct-field.go</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.struct-field.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b([a-z]+)(:)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(struct)\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.struct.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.declaration.struct.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.struct.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#struct-field</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#struct-tags</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-call</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable-dot-access</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.pointer.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\.)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(type)[\s\t]*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type-block.begin.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type-block.end.go</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type-block.go</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#struct-declaration</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interface-declaration</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.go</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.type.go</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.type.pointer.go</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.package.go</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.name.type.go</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^[\s\t]*([a-zA-Z0-9_]+)[\s\t]+((\*)?(?:([a-zA-Z0-9_]+)(\.))?[a-zA-Z0-9_]+)[\s\t]*$</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b([a-zA-Z0-9_]+)[\s\t]+(?=[a-zA-Z0-9_\&lt;\[\*])</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.go</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>storage.type.go</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.type.pointer.go</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>entity.name.package.go</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.type.go</string>
										</dict>
									</dict>
									<key>match</key>
									<string>\b((\*)?([a-zA-Z0-9_])?(\.)[a-zA-Z0-9_]+)\b</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type-statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(type)[\s\t]+([a-zA-Z0-9_]+)[\s\t]+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storage-types</string>
				</dict>
			</array>
		</dict>
		<key>var-and-const-blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(var|const)[\s\t]*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.var-block.begin.go</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.block.var.go</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.var-block.end.go</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#assignment-expr</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b([a-zA-Z0-9_]+)\b</string>
							<key>name</key>
							<string>variable.other.go</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-and-const-statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(var|const)[\s\t]+([a-zA-Z0-9_]+)[\s\t]*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.go</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.go</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#assignment-expr</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variable-dot-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.)([A-Za-z0-9_]+)(?=\s*[^\(])</string>
					<key>name</key>
					<string>variable.dot-access.go</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.go</string>
	<key>uuid</key>
	<string>1ceaa75c-b61d-11e2-ba93-138feb5db969</string>
</dict>
</plist>
